# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 106875cee7647549043f6d426f51173333a03c5fb66f8c3313528da94c1a9356752ce1ebfcb498fccfecea71d2df023ca7666528fdd6cae4fd5b15cf0f4e372b

test:
  secret_key_base: 12d7c57eec41fd72929cec31b5af9b618e85b23c2b4b1c9e6b533f0dcff31766cae47d898a24f05211b2494f81f35cf6d151ef06fbddf0c7dbe692ef09fd279c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
